[package]
name = "msgpck"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = { version = "0.2.17", default-features = false }
msgpck_derive = { version = "0.1.0", path = "../msgpck_derive", optional = true }
heapless07 = { package = "heapless", version = "0.7.16", optional = true }
thiserror = { version = "1.0.50", optional = true }

[features]
default = ["std", "derive", "heapless07"]
heapless07 = ["dep:heapless07"]
alloc = []
debug = []
std = ["debug", "alloc", "num-traits/std", "dep:thiserror"]
derive = ["dep:msgpck_derive"]

[dev-dependencies]
paste = "1.0.14"
proptest = "1.3.1"
proptest-derive = "0.4.0"
pretty-hex = "0.3.0"
