[package]
name = "msgpck"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = { version = "0.2.17", default-features = false }

[features]
default = ["std"]
alloc = []
std = ["debug", "alloc", "num-traits/std"]
debug = []
